listen-address: "0.0.0.0:25566"
motd: "Click here to start your own custom server!"
favicon: "./favicon.png"
login-flow:
  welcome-msg: "Welcome!\nTo start playing, please register using this secret link:\n%s"
  backend-not-ready-msg: "§eServer is starting...\n§7Please wait %s"
